/* eslint-disable @typescript-eslint/explicit-function-return-type */

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Providers } from '../providers'
import { NavBar } from '../../components/Navbar'
import { Sibebar } from '../../components/Sidebar'
import { Grid, GridItem } from '@chakra-ui/react'

const inter = Inter({ subsets: ['latin'], variable: '--font-inter' })

export const metadata: Metadata = {
  title: 'Back Office - ZenFlow',
  description: 'Generated by Facundo Martin'
}

export default function RootLayout ({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className={inter.variable}>
      <body className='layout-structure'>
        <Providers>
          <Grid h="100vh"
            templateAreas={`"navbar navbar"
                            "sidebar main"
                            "sidebar main"`}
            gridTemplateRows={'55px 1fr 1fr'}
            gridTemplateColumns={'240px 1fr'}>
            <GridItem area="navbar">
              <NavBar />
            </GridItem>
            <GridItem area="sidebar" h="100%">
              <Sibebar />
            </GridItem>
            <GridItem area="main" h="100%">
              {children}
            </GridItem>
          </Grid>
        </Providers>
      </body>
    </html>
  )
}
