/* eslint-disable @typescript-eslint/explicit-function-return-type */
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Providers } from '../providers'
import { NavBar } from '../../components/Navbar'
import { Sibebar } from '../../components/Sidebar'
import { Grid, GridItem } from '@chakra-ui/react'
import { Suspense } from 'react'
import { LayoutSkeleton } from '@/src/components/Skeleton/Layout'

const inter = Inter({ subsets: ['latin'], variable: '--font-inter' })

export const metadata: Metadata = {
  title: 'Back Office - ZenFlow',
  description: 'Generated by Facundo Martin'
}

export default function RootLayout ({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className={inter.variable}>
      <head>
        <link rel="icon" href="/static/zenflow1.png" sizes="any" style={{ borderRadius: '100' }} />
      </head>
      <body className='layout-structure'>
        <Providers>
          <Suspense fallback={<LayoutSkeleton />}>
            <Grid h="100vh" overflow={'hidden'}
              templateAreas={{
                base: `"navbar"
                       "main"`,
                md: `"navbar navbar"
                     "sidebar main"
                     "sidebar main"`
              }}
              gridTemplateRows={{
                base: '55px 1fr',
                md: '55px 1fr 1fr'
              }}
              gridTemplateColumns={{
                base: '1fr',
                md: '240px 1fr'
              }}>
              <GridItem area="navbar">
                <NavBar />
              </GridItem>
              <GridItem area="sidebar" h="100%" display={{ base: 'none', md: 'block' }}>
                <Sibebar />
              </GridItem>
              <GridItem area="main" h="100%" pt={{ base: 12, md: 0 }}>
                {children}
              </GridItem>
            </Grid>
          </Suspense>
        </Providers>
      </body>
    </html>
  )
}
